{
  parserClass="com.github.tyrrx.buntenachtaddr.language.parser.AddRParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="AddR"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.tyrrx.buntenachtaddr.language.psi"
  psiImplPackage="com.github.tyrrx.buntenachtaddr.language.psi.impl"

  elementTypeHolderClass="com.github.tyrrx.buntenachtaddr.language.psi.AddRTypes"
  elementTypeClass="com.github.tyrrx.buntenachtaddr.language.psi.AddRElementType"
  tokenTypeClass="com.github.tyrrx.buntenachtaddr.language.psi.AddRTokenType"
}

addRFile ::= module
module ::= (statement endOfStatement)*
endOfStatement ::= SEMICOLON | SEMICOLON <<eof>>
statement ::= valueAssignment

valueAssignment ::= VAL identifier EQ expression {mixin="AddRValueAssignmentMixin" implements="AddRNamedIdentifierOwner"}

expression ::= atom (PLUS expression)+ | atom

atom ::= literal | symbolReference

literal ::= NUMBER_LITERAL

symbolReference ::= identifier {mixin="AddRSymbolReferenceMixin" implements="AddRNamedElement"}

identifier ::= ID {mixin="AddRIdentifierMixin" implements="AddRNamedElement"}
//symbolReference ::= IDENTIFIER {mixin="com.github.tyrrx.buntenachtaddr.language.psi.impl.AddRSymbolReferenceMixin" implements="AddRNamedElement"}