{
  parserClass="com.github.tyrrx.buntenachtaddr.language.parser.AddRParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="AddR"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.tyrrx.buntenachtaddr.language.psi"
  psiImplPackage="com.github.tyrrx.buntenachtaddr.language.psi.impl"

  elementTypeHolderClass="com.github.tyrrx.buntenachtaddr.language.psi.AddRTypes"
  elementTypeClass="com.github.tyrrx.buntenachtaddr.language.psi.AddRElementType"
  tokenTypeClass="com.github.tyrrx.buntenachtaddr.language.psi.AddRTokenType"
}

addRFile ::= (statement endOfLine)*
endOfLine ::= NEW_LINE+ | NEW_LINE+ <<eof>> | <<eof>>
statement ::= assignment expression
assignment ::= VAL IDENTIFIER EQ
expression ::= binaryExpression | atom
binaryExpression ::= atom (PLUS expression)+
atom ::= literal | assignmentRef
literal ::= NUMBER_LITERAL
assignmentRef ::= IDENTIFIER